### ISSUE TITLE
compatible with last HA  2021.12.3 ?

### ISSUE THREAD

**Issue by zekje** [jesserockz/ha-leafspy#10]
hi, i have tried to install ha-leafspy on two way : 
create leafspy folder , download all files
or by hacs and download leafspy

after reboot, i have not found leaf spy a the 7. configuration  ( In the HA UI go to "Configuration" -> "Integrations" click "+" and search for "Leaf Spy" )   no "leaf spy" found  , so i can't continue ...

**Comment by zekje** [comment]
i have installed 0.1.2 by HACS and it's OK .  now i ll try to update to 0.1.6

**Comment by jesserockz** [comment]
I use this everyday and generally keep my HA instance up to date, and I have not noticed any errors so far.

**Comment by zekje** [comment]
i didn't konw how it fail last time ( perhaps rest of prévious installation ) ,
when i have installed 0.1.2 ( by hacs ) i have the information with code :)
i have updated to 0.1.6 ( and 0.1.7 today ) and it's works fine (thank's)

i close this issue
