### ISSUE TITLE
Other parameters

### ISSUE THREAD

**Issue by WojtaszekMarek** [jesserockz/ha-leafspy#11]
Hello
Where are other parameters like i.e SOH, SOC number of L1/L2 charges, QC and etc, start and end trip date and time? Number of kilometers?

**Comment by jesserockz** [comment]
`SOC` is exposed as `battery_level`
`SOH` is exposed as `amp_hours`

The others are not sent to the server and I don't think you can change that.

Linked is a list of the params sent via the HTTP request and the attributes they map to:

https://github.com/jesserockz/ha-leafspy/blob/2caf25ef50ccefc40febead8f2b0f4d6dfb45c98/custom_components/leafspy/device_tracker.py#L164-L187
