### ISSUE TITLE
Integration for the Idiot (me)

### ISSUE THREAD

**Issue by UniKyrn** [jesserockz/ha-leafspy#12]
Assume I'm an idiot, mostly. :)

1) I have the integration installed.
2) I bought Leaf Spy Pro and a dongle.
3) I can see all the values in the app.
4) I configured the server.

How do I get my first Card showing values in HA?  I created a new desktop and added a card, but I do not see a device_tracker Entity for my car.  Does it not get created until the first push of data from the App into HA?

This is where I get stuck, sorry.

**Comment by jesserockz** [comment]
Yes it will only show up once the app pushes data through.

Then all the data is available as attributes on the device_tracker entity.

**Comment by UniKyrn** [comment]
Thank You.

**Comment by UniKyrn** [comment]
And I'm still missing something.  Leaf Spy is logging data to Dropbox, so it's talking to my car.  It's not talking to HA though via the server config.

Is the URL just http(s)://IP-Addr:8123/  ?
Do I need to create a user in HA that matches the server config?
Any permissions that user needs?

I'm not seeing the device_tracker entity get created and I'm not seeing anything in the log files.

Sorry to keep pestering you, I couldn't find a clear example of how to set this up.

**Comment by UniKyrn** [comment]
Oh, now this is a twist.  I'm testing local while inside my home network.  Android on the phone is blocking the connection because it is cleartext (http), not https, and there does not seem to be a way to change that.

Looks like we use https or go home empty handed.

**Comment by jesserockz** [comment]
I have not tested with http as my HA instance is available with the same https domain inside and outside my network. Can also use Home Assistant Cloud url if you subscribe.
