### ISSUE TITLE
The integration doesn't work

### ISSUE THREAD

**Issue by dcarotenuto** [jesserockz/ha-leafspy#14]
I installed the integration using the documentation and in my HA I'm able to show the leaf spy icon in integrations panel, but there is no other info or component shown in the ha interface, I have to insert something in configuration,yaml file? There is no documention about that.

What is the webhook to insert in leaf spy pro app?

Thanks

**Comment by jesserockz** [comment]
When you add the integration, the instructions are provided as a part of the config flow. Remove it and add it again to see them, including the webhook and password.

**Comment by dcarotenuto** [comment]
Reading the install instruction here, I have to copy the leafspy dir in custom_componets, after that, rebooting ha in my log I have the following

[homeassistant.loader] Loaded leafspy from custom_components.leafspy

[homeassistant.loader] You are using a custom integration leafspy which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

[homeassistant.loader] Loaded updater from homeassistant.components.updater
2022-02-27 15:26:20 INFO (MainThread) [homeassistant.bootstrap] Domains to be set up: {'recorder', 'zone', 'updater', 'group', 'weather', 'device_tracker', 'cert_expiry', 'webhook', 'local_ip', 'alexa', 'dhcp', 'frontend', 'system_log', 'default_config', 'script', 'sun', 'lovelace', 'leafspy', 'config_check', 'websocket_api', 'upnp', 'person', 'tag', 'scene.....

[homeassistant.setup] Setting up leafspy
[homeassistant.setup] Setup of domain leafspy took 0.0 seconds

I found in .storage/core.config_entries the following
 {
                "entry_id": "e012aecf589b47f9aee9c0eb40c70ed4",
                "version": 1,
                "domain": "leafspy",
                "title": "Leaf Spy",
                "data": {
                    "secret": "xxxxxxxxxxxxxxxxxx"
                },
                "options": {},
                "system_options": {
                    "disable_new_entities": false
                },
                "source": "user",
                "connection_class": "local_push",
                "unique_id": null,
                "disabled_by": null
            },
but nothing about webhook or other info displayed in log or in lovelace interface.

In leafspy app I set the secret value and in url parameter the address of my ha system, but nothing happens in HA.

Can you please add something more explanation?

Thank a lot.

**Comment by jesserockz** [comment]
![Screenshot from 2022-02-28 09-31-00](https://user-images.githubusercontent.com/3060199/155898814-db44e81b-e60d-4de1-bc32-f11f6af5effe.png)

![Screenshot from 2022-02-28 09-31-07](https://user-images.githubusercontent.com/3060199/155898816-16c9be99-c83e-41d2-a54c-0d8ac958f6ae.png)

![Screenshot from 2022-02-28 09-31-12](https://user-images.githubusercontent.com/3060199/155898817-e87a9941-61a6-461d-96ed-e67c1d348d2e.png)

The instructions are there, and you can see the URL at the bottom of the config flow. (It will show your personal external hostname there, that is just my local dev instance.

**Comment by dcarotenuto** [comment]
Thanks a lot for explanation, now is clear.
In my case the submit button in integration is not shown.
Solved.
