### ISSUE TITLE
Instructions for configuration of android app

### ISSUE THREAD

**Issue by haberda** [jesserockz/ha-leafspy#2]
**Is your feature request related to a problem? Please describe.**
It is unclear how to configure the leafspy app to use this integration.

**Describe the solution you'd like**
Can you provide some basic instructions on how to configure the app to report back to this integration?

**Comment by haberda** [comment]
Thanks for adding the documentation.

I think my problem is deeper. I noticed that when I installed it originally I was not presented with anything. Now seeing the documentation you added, it looks like I should be getting a prompt to get the webhook URL and secret. But when I install the integration, after I click submit, the integration is just added. I noticed that if I look at the config json in the .storage folder that I can get the secret, but I still don't have the webhook.

So I turned on debug logging and got this:
```2021-02-03 17:10:58 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection] [139936993610048] Sending {'id': 55, 'type': 'result', 'success': True, 'result': {'resources': {'component.leafspy.config.abort.one_instance_allowed': 'Only a single instance is necessary.', 'component.leafspy.config.create_entry.default': '\n\nOpen the Leaf Spy app, go to `Menu` -> `Settings` and scroll down to `Server`. \nChange the following settings:\n - `Enable`: Yes\n - `Send Interval` can be whatever you prefer.\n - `ID`: `<Car Name>`\n - `PW`: {secret}\n - `Http` or `Https` depending on the access to your Home Assistant install.\n - `URL`: {url} - Note: **Do not** add http or https to the URL.', 'component.leafspy.config.step.user.description': 'Are you sure you want to set up Leaf Spy?', 'component.leafspy.config.step.user.title': 'Set up Leaf Spy'}}}```

This seems to indicate that there is already something setup, but I had removed the integration->restarted hass->then reinstalled it. I even removed it from HACS. Anyway, is it detecting that a webhook exists somewhere and then just aborting?

**Comment by jesserockz** [comment]
Hmm, yeah I just tried that myself on a fresh HA and the screen just goes dark... Ill take another look at that part

**Comment by haberda** [comment]
Awesome! Thanks!

**Comment by jesserockz** [comment]
I fixed it. My string description that was supposed to show up was broken because it had `string` and I looked at others which had `'string'` and that seems to work 🤷 

Try 0.1.3 now and close this if its working for you

**Comment by haberda** [comment]
Cool, with this version I get the prompt with the URL and secret. Now to test the app

Thanks!
