### ISSUE TITLE
Non-secure Leaf Spy API Blocked

### ISSUE THREAD

**Issue by mcnelson** [jesserockz/ha-leafspy#22]
First off, my apologies for bringing up a Leaf Spy issue. I was hoping this would still be acceptable because it's preventing me from using this integration.

My HA runs completely locally, and when I put in the endpoint given by this integration, Leaf Spy throws error "UnknownServiceException: CLEARTEXT communication to (local IP) not permitted by network security policy". In other words, we have to use HTTPS, which doesn't make sense for LAN communication.

Anyone hit this too? Did you just end up making an HTTPS endpoint? I don't want to expose my HA to the world. Whoever decided to disallow insecure traffic appears to have forgotten about local usage.

**Comment by Happyboy0980** [comment]
Same issue here, did you find a solution?

**Comment by Happyboy0980** [comment]
Meanwhile, figured out this is not related to Leaf Spy or this integration, but from Android 8 this is "blocked". Use now an old android 5 device only for this, than the "error's" are gone.

**Comment by mcnelson** [comment]
I actually ended up contacting the Leafspy author and he actually added some configuration that cleared the insecure communication with Android's security checks. Latest Leafspy should work, though I haven't tested it yet.
