### ISSUE TITLE
WARNING hass.helpers.dispatcher is deprecated and will stop working in HA 2024.11 - __init__.py line 46

### ISSUE THREAD

**Issue by SJLBoulder** [jesserockz/ha-leafspy#25]
I'm a new user. Just installed the LeafSpy integration. Thank you.

I see a warning that a HA service/function is deprecated and will stop working later this year:

2024-07-01 16:17:07.730 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'leafspy' accesses hass.helpers.dispatcher. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from dispatcher directly at custom_components/leafspy/__init__.py, line 46: hass.helpers.dispatcher.async_dispatcher_connect(, please create a bug report at https://github.com/jesserockz/ha-leafspy/issues

**Comment by caitotheonlypotato** [comment]
I also have a few mentioning deprecation from 2004.9

Detected that custom integration 'leafspy' accesses hass.helpers.dispatcher. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from dispatcher directly at custom_components/leafspy/__init__.py, line 46: hass.helpers.dispatcher.async_dispatcher_connect(, please create a bug report at https://github.com/jesserockz/ha-leafspy/issues


Detected that custom integration 'hacs' accesses hass.components.frontend. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to import functions used from frontend directly at custom_components/hacs/frontend.py, line 68: hass.components.frontend.async_register_built_in_panel(, please create a bug report at https://github.com/hacs/integration/issues


Detected that custom integration 'reolink_dev' accesses hass.components.webhook. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to import functions used from webhook directly at custom_components/reolink_dev/base.py, line 496: webhook_id = self._hass.components.webhook.async_generate_id(), please create a bug report at https://github.com/fwestenberg/reolink_dev/issues


Detected that custom integration 'hacs' accesses hass.helpers.event. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from event directly at custom_components/hacs/base.py, line 630: self.hass.helpers.event.async_track_time_interval(, please create a bug report at https://github.com/hacs/integration/issues
