### ISSUE TITLE
Latest update and HA 2024.8.x

### ISSUE THREAD

**Issue by caitotheonlypotato** [jesserockz/ha-leafspy#26]
Hi.

I've been absolutely thrilled with the features this component brings to HA for the Leaf, and it's worked flawlessly up until the last update .

Essentially, I updated to OS13.0, HA 2024.8.1 and the latest version of this component to get around the upcoming deprecations. 

On restart of the system, Leafspy component no longer works.  The app can't communicate with the server.

When I revert to my last installed version 0.2.1 of Leafspy component, it starts to work again

On the latest version I see this on the phone in the car
![image](https://github.com/user-attachments/assets/ff4403f1-5538-457b-850f-a3a6578ba5f8)

I see the following error logs in HA
![image](https://github.com/user-attachments/assets/f390b80d-7edd-4cb4-bf52-28322015e1c0)

If you need some further input, please let me know

**Comment by wtadler** [comment]
I can't test right now, but I think that [this line](https://github.com/jesserockz/ha-leafspy/blob/main/custom_components/leafspy/__init__.py#L108) needs to be changed from `async_dispatcher_send(DOMAIN, hass, context, message)` to `async_dispatcher_send(hass, DOMAIN, context, message)`. My bad for not testing completely before issuing the release.

Do you want to try making this change in your local version of `/homeassistant/custom_components/leafspy/__init__.py`, restart HA, test, and if it works, open a PR?

**Comment by caitotheonlypotato** [comment]
> I can't test right now, but I think that [this line](https://github.com/jesserockz/ha-leafspy/blob/main/custom_components/leafspy/__init__.py#L108) needs to be changed from `async_dispatcher_send(DOMAIN, hass, context, message)` to `async_dispatcher_send(hass, DOMAIN, context, message)`. My bad for not testing completely before issuing the release.
> 
> Do you want to try making this change in your local version of `/homeassistant/custom_components/leafspy/__init__.py`, restart HA, test, and if it works, open a PR?

Hi.

I'll give it a go

**Comment by caitotheonlypotato** [comment]
OK, making the change does fix the error, however no data makes its way to the sensor or the attributes thereof.

**Comment by wtadler** [comment]
Sorry about this. Can you try updating to 0.2.4 and see if that fixes it?

**Comment by caitotheonlypotato** [comment]
> Sorry about this. Can you try updating to 0.2.4 and see if that fixes it?

Hi.  This update brings the functionality back to normal, many thanks.
One note is that the version number reported back to HA is still 0.2.3 in [Settings / Integrations ]

![image](https://github.com/user-attachments/assets/62d42395-ddd9-42bd-83e8-7af55634cc90)

whereas in [ HACS / Integrations ], downloaded version shows 0.2.4

![image](https://github.com/user-attachments/assets/990661e0-7f3c-46b1-a1c6-babaf5697187)

Super Grateful!
Many Thank!
