### ISSUE TITLE
Leafspy does not connect with the server

### ISSUE THREAD

**Issue by enduring78** [jesserockz/ha-leafspy#36]
## Version of the custom_component

0.2.4

## Configuration

```yaml
Error processing leafspy webhook
Traceback (most recent call last):
  File "/config/custom_components/leafspy/__init__.py", line 105, in get
    if not hmac.compare_digest(message['pass'], context.secret):
                               ~~~~~~~^^^^^^^^
KeyError: 'pass'


```
Note: this is the only log I get in the debug log, other than the log pasted above

## Describe the bug
My phone has SocketException errors when connecting to the Leafspy integration in HA. When I manually pen the API URL, I het HTTP error 500. On my firewall, I cn see connections coming trough so the phone can reach my Home Assistant instance. I can also access the Home Assistant app just fine.

## Debug log

```text
2024-12-14 15:43:14.012 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry Leaf Spy for leafspy
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 855, in async_unload
    result = await component.async_unload_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/leafspy/__init__.py", line 60, in async_unload_entry
    hass.data[DOMAIN].pop(entry.entry_id)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '01JF2SV3PWMJWQ0F3HMA2SSR27'

```

**Comment by wtadler** [comment]
Can you try removing the integration, restarting HA, and reinstalling the integration? You'll have to also adjust your LeafSpy configuration--the password, at least.

**Comment by enduring78** [comment]
Hi, 
Yes, I have removed and re-added the integration multiple times. I'll try removing the entire custom component in a few minutes, to see if that changes anything.

Edit: after reinstalling the custom component (and restarting Home Assistant in between) it still does not work

**Comment by Chaoscontrol** [comment]
This seems to be a wrong password type of error tbh.

**Comment by wtadler** [comment]
If the integration was working before and stopped working, I'm not sure what could have possibly changed. In the latest release, I've tried to make the setup directions clearer. Can you try updating to that version and reinstalling, following the directions closely?

**Comment by enduring78** [comment]
Hi, 

I have tested with another phone and it indeed worked fine. After experimenting a lot more with my own phone, I have pinpointed the issue: Leafspy does not like my VPN app, even though the VPN app permits local network connections.

I am sorry for wasting your guys' time :(

**Comment by wtadler** [comment]
No worries!
