### ISSUE TITLE
Suggestion for improving documentation

### ISSUE THREAD

**Issue by umbjm1** [jesserockz/ha-leafspy#40]
I could not see any device or entities after repeated installations, so a log seems irrelevant.

The documentation was not clear. I suggest editing the "Server" panel instructions for LeafSpy settings to state:

"Server" setting panel:
"Enable" checked (not sure if this matters--I interpreted the instructions as referring to this checkbox)
"Server" popup set to "A" (again, not sure if this matters, but it was checked and I never changed it)

"A : Enable" checked. <---This was the key to making it work for me. Nothing in the instructions suggested that it is relevant.

Thanks!

**Comment by wtadler** [comment]
Good note, thank you! Addressed by cee305b.

Apparently LeafSpy allows you to configure and toggle up to 4 servers. These new instructions help the user make sure that server A is configured and toggled on.
