### ISSUE TITLE
Where is the secret for leaf spy app integration?

### ISSUE THREAD

**Issue by dcarotenuto** [jesserockz/ha-leafspy#8]
I integrate the component in my HA, but there isn't any secret number to use for configure the app. Can you help me? Thanks

**Comment by jesserockz** [comment]
The secret is only shown when you first set up the integration. 

The only way to find it later is to look at the config_entries file in the `.storage` folder.

**Comment by hiekkis123** [comment]
I also dont seem to find the secret, I didnt see it when setting up integration. My /config/custom_components/leafspy folder seems to have correct files. I also tried to look at: /config/.storage/core.config_entries, but I dont find here anything that would be related to leafspy. Any help?
